manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: openthreadsim
      url-base: https://github.com/loganrex

  projects:
    - name: openthread-sim-drivers
      remote: openthreadsim
      revision: main
      path: modules/openthread-sim-drivers
  
  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests